FROM mcr.microsoft.com/playwright/python:v1.45.0
RUN pip install playwright
RUN pip install pytest-playwright
RUN pip install pytest-xdist


# [Optional] Set the default user. Omit if you want to keep the default as root.
USER pwuser