name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 19
        cache: npm
        cache-dependency-path: ./frontend/npm.lock

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps

    - name: Run your tests
      run: |
        mkdir -p test-results
        pytest --junitxml=test-results/results.xml --tracing=retain-on-failure

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/results.xml

    - name: Upload Playwright traces
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-traces
        path: test-results/
