name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chromium, firefox, webkit]
        
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps ${{ matrix.browser }}

    # Install Testmo CLI tool locally (then use npx testmo .. to run it)
    - run: npm install --no-save @testmo/testmo-cli

    - name: Run your tests
      run: |
        mkdir -p test-results
        pytest --browser ${{ matrix.browser }} --junitxml=test-results/${{ matrix.browser }}_results.xml --tracing=retain-on-failure 

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.browser }}_test-results
        path: test-results/${{ matrix.browser }}_results.xml

    - name: Upload Playwright traces
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.browser }}_playwright-traces
        path: test-results/

    # report results to Testmo
    - run: |
        npx testmo automation:run:submit \
          --instance "$TESTMO_URL" \
          --project-id 1 \
          --name "CICD" \
          --source "functiontest" \
          --results test-results/*.xml
      env:
        TESTMO_URL: ${{ secrets.TESTMO_URL }}
        TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
